# Question 9

In [1]:
import numpy as np
import pandas as pd

### I. Numpy

#### 1. Concatenate two 2d arrays.

In [28]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

concatenated_array = np.concatenate((array1, array2), axis=1)
print(concatenated_array)

concatenated_array = np.concatenate((array1, array2), axis=0)
print(concatenated_array)

concatenated_array = np.hstack((array1, array2))
print(concatenated_array)

concatenated_array = np.vstack((array1, array2))
print(concatenated_array)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### 2. Use Universal functions.

In [ ]:
help(np.ufunc)

#### 3. Create a vector of range 0 to 20 and numbers should be negative from range 9 to 15.

In [29]:
import numpy as np

vector = np.arange(21)

vector[9:16] *= -1

print(vector)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


### II. Pandas

#### 1. Create a Dataframe with default index and change the index with specific column.


In [30]:
data = {'column1': [1, 2, 3], 'column2': ['a', 'b', 'c']}
df = pd.DataFrame(data)
display(df)

df.set_index('column1', inplace=True)
display(df)

column1 column2
0        1       a
1        2       b
2        3       c

column2
column1        
1             a
2             b
3             c

#### 2. Calculate frequency counts of unique elements.

In [31]:
data = {'name': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob'],
        'age': [25, 30, 28, 25, 30]}
df = pd.DataFrame(data)

counts_name = df['name'].value_counts().reset_index()
display(counts_name)

name  count
0    Alice      2
1      Bob      2
2  Charlie      1

#### 3. Retrieve top 3 rows of a dataframe

In [32]:
display(df.head(3))

name  age
0    Alice   25
1      Bob   30
2  Charlie   28

### III. National University Rankings.

In [4]:
data = pd.read_csv("National_Universities_Rankings.csv")

#### 1. Find the universities along with state whose fee is in between 25,000 to 30,000.

In [5]:
data["TuitionFees"] = [int("".join(filter(str.isdigit, s))) for s in data["Tuition and fees"]]

df = data[(data["TuitionFees"] >= 25000) & (data["TuitionFees"] <= 30000)]

display(df[['Name', 'Location', 'Tuition and fees']])

Name             Location  \
50                               University of Florida      Gainesville, FL   
53                     Ohio State University--Columbus         Columbus, OH   
57                               University of Georgia           Athens, GA   
60                   Purdue University--West Lafayette   West Lafayette, IN   
68                            University of Pittsburgh       Pittsburgh, PA   
75               Texas A&M University--College Station  College Station, TX   
77                                       Virginia Tech       Blacksburg, VA   
84                                  University of Iowa        Iowa City, IA   
92            North Carolina State University--Raleigh          Raleigh, NC   
97                        Stony Brook University--SUNY      Stony Brook, NY   
98                                   Auburn University           Auburn, AL   
101                        University at Buffalo--SUNY          Buffalo, NY   
103                              University of Alabama       Tuscaloosa, AL   
112                             University of Missouri         Columbia, MO   
116                                 University of Utah   Salt Lake City, UT   
119                                  Temple University     Philadelphia, PA   
121                               University of Kansas         Lawrence, KS   
128                    Arizona State University--Tempe            Tempe, AZ   
130                          Colorado State University     Fort Collins, CO   
133                             University of Kentucky        Lexington, KY   
135            Louisiana State University--Baton Rouge      Baton Rouge, LA   
138                         Rutgers University--Newark           Newark, NJ   
140                           University of Cincinnati       Cincinnati, OH   
143                            Oregon State University        Corvallis, OR   
144                        Washington State University          Pullman, WA   
155                    University of Illinois--Chicago          Chicago, IL   
157                University of Massachusetts--Lowell           Lowell, MA   
161                         University of Rhode Island         Kingston, RI   
164                  Maryville University of St. Louis         St Louis, MO   
165        Missouri University of Science & Technology            Rolla, MO   
170                                   Edgewood College          Madison, WI   
175                              Ball State University           Muncie, IN   
176                                Lipscomb University        Nashville, TN   
182                                 Andrews University  Berrien Springs, MI   
184                                University of Maine            Orono, ME   
190                           Robert Morris University    Moon Township, PA   
194                              University of Houston          Houston, TX   
195                        Western Michigan University        Kalamazoo, MI   
196  Indiana University-Purdue University--Indianap...     Indianapolis, IN   
197                                  Lesley University        Cambridge, MA   
199                     University of Colorado--Denver           Denver, CO   
203                          Louisiana Tech University           Ruston, LA   
211                            Old Dominion University          Norfolk, VA   
214                          Dallas Baptist University           Dallas, TX   
216                       Nova Southeastern University   Ft. Lauderdale, FL   
217           Southern Illinois University--Carbondale       Carbondale, IL   
221                            Gardner-Webb University  Boiling Springs, NC   
227                  University of Missouri--St. Louis        St. Louis, MO   

    Tuition and fees  
50          $28,666   
53          $29,229   
57          $29,844   
60          $28,804   
68          $29,758   
75          $28,768   
77          $29,3

#### 2. Find university where undergraduate enrollement is more than 25000 containing in-state students.

In [11]:
data["UndergradEnrollment"] = [int("".join(filter(str.isdigit, s))) for s in data["Undergrad Enrollment"]]

df = data[data['UndergradEnrollment'] > 25000][data['In-state'].notnull()]

display(df[['Name', 'Location', 'In-state', 'Undergrad Enrollment']])

Name             Location  \
21               University of California--Berkeley         Berkeley, CA   
24            University of California--Los Angeles      Los Angeles, CA   
27                University of Michigan--Ann Arbor        Ann Arbor, MI   
42                 University of California--Irvine           Irvine, CA   
44                  University of California--Davis            Davis, CA   
45              University of California--San Diego         La Jolla, CA   
46         University of Illinois--Urbana-Champaign        Champaign, IL   
48                 University of Wisconsin--Madison          Madison, WI   
50                            University of Florida      Gainesville, FL   
52   Pennsylvania State University--University Park  University Park, PA   
53                  Ohio State University--Columbus         Columbus, OH   
54                         University of Washington          Seattle, WA   
57                            University of Georgia           Athens, GA   
58                      University of Texas--Austin           Austin, TX   
60                Purdue University--West Lafayette   West Lafayette, IN   
63             University of Maryland--College Park     College Park, MD   
69                Rutgers University--New Brunswick       Piscataway, NJ   
72             University of Minnesota--Twin Cities      Minneapolis, MN   
75            Texas A&M University--College Station  College Station, TX   
77                                    Virginia Tech       Blacksburg, VA   
82                        Michigan State University     East Lansing, MI   
86                  Indiana University--Bloomington      Bloomington, IN   
91                         Florida State University      Tallahassee, FL   
93                  University of Colorado--Boulder          Boulder, CO   
103                           University of Alabama       Tuscaloosa, AL   
109                    University of South Carolina         Columbia, SC   
110                           Iowa State University             Ames, IA   
112                          University of Missouri         Columbia, MO   
119                               Temple University     Philadelphia, PA   
127                           University of Arizona           Tucson, AZ   
128                 Arizona State University--Tempe            Tempe, AZ   
135         Louisiana State University--Baton Rouge      Baton Rouge, LA   
140                        University of Cincinnati       Cincinnati, OH   
147                      San Diego State University        San Diego, CA   
162                     University of South Florida            Tampa, FL   
179                           Texas Tech University          Lubbock, TX   
180                   University of Central Florida          Orlando, FL   
194                           University of Houston          Houston, TX   
201          California State University--Fullerton        Fullerton, CA   
230                           Utah State University            Logan, UT   

     In-state Undergrad Enrollment  
21   $13,509                27,496  
24   $12,836                29,585  
27   $13,856                28,312  
42   $14,750                25,256  
44   $14,046                28,384  
45   $14,705                26,590  
46   $15,698                33,368  
48   $10,488                31,662  
50    $6,389                35,043  
52   $17,900                40,742  
53   $10,037                45,289  
54   $10,753                31,063  
57   $11,634                27,547  
58    $9,806                39,619  
60   $10,002                29,497  
63   $10,181                27,443  
69   $14,372                35,484  
72   $13,790                34,071  
75   $10,176                48,960  
77   $12,852                25,384  
82   $14,070                39,143  
86   $10,388                38,364  
91    $9,507                32,706  
93   $11,531                27,010  
103  

#### 3. Find the states where universities are located in three or more cities.

In [12]:
data["state"] = [i[-2:] for i in data['Location']]

city_counts = data.groupby("state")["Name"].count()

display(city_counts[city_counts >= 3].reset_index())

state  Name
0     AL     4
1     CA    22
2     CO     5
3     CT     3
4     DC     5
5     FL     7
6     GA     4
7     IL    11
8     IN     5
9     LA     3
10    MA    15
11    MD     3
12    MI     6
13    MO     7
14    MS     3
15    NC     8
16    NJ     7
17    NY    21
18    OH     9
19    OK     3
20    PA    12
21    TN     5
22    TX    10
23    UT     3
24    VA     7
25    WA     3
26    WI     3

#### 4. Find max and min tuition fee in each state.

In [13]:
display(data.groupby('state').agg({'Tuition and fees': ['max', 'min']}))

Tuition and fees          
                   max       min
state                           
AK            $22,469   $22,469 
AL            $28,840   $17,654 
AR            $23,168   $23,168 
AZ            $30,025   $25,458 
CA            $52,217   $17,209 
CO            $46,362   $28,374 
CT            $49,480   $35,858 
DC            $51,950   $24,908 
DE            $31,420   $31,420 
FL            $47,004   $17,325 
GA            $47,954   $29,844 
HI            $33,764   $33,764 
IA            $28,413   $21,483 
ID            $22,040   $22,040 
IL            $52,491   $20,886 
IN            $49,685   $25,428 
KS            $25,932   $23,429 
KY            $26,334   $24,626 
LA            $51,010   $25,851 
MA            $52,430   $19,270 
MD            $50,410   $24,492 
ME            $29,498   $29,498 
MI            $43,476   $23,670 
MN            $39,594   $22,210 
MO            $49,770   $22,714 
MS            $22,012   $16,094 
MT            $24,562   $23,042 
NC            $51,265   $20,193 
ND            $19,790   $18,899 
NE            $23,148   $23,148 
NH            $51,438   $31,424 
NJ            $48,838   $20,318 
NM            $21,302   $21,234 
NV            $21,052   $21,052 
NY            $55,056   $17,620 
OH            $46,006   $18,332 
OK            $38,796   $20,978 
OR            $33,442   $28,846 
PA            $52,040   $25,994 
RI            $51,367   $28,852 
SC            $32,796   $31,282 
SD            $11,688   $11,403 
TN            $45,610   $24,800 
TX            $50,358   $22,861 
UT             $5,300   $19,772 
VA            $45,066   $27,028 
VT            $40,364   $40,364 
WA            $38,940   $25,673 
WI            $38,470   $27,530 
WV            $21,432   $21,432 
WY            $16,215   $16,215