# Question 6

In [2]:
import numpy as np
import pandas as pd

### I. Numpy

#### 1. How to randomly place 'P' element in a 2D matrix.

In [36]:
matrix = np.zeros([3,3], dtype=int)
print(matrix)

x = np.random.randint(0, matrix.shape[0])
y = np.random.randint(0, matrix.shape[1])

P = 5
matrix[x][y] = P
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 5]
 [0 0 0]
 [0 0 0]]


#### 2. How to subtract the mean of each row of a matrix.

In [43]:
def subtract_row_mean(array):
    return array - np.mean(array, axis=1, keepdims=True)

array = np.array([[1, 8, 3], [4, 5, 9], [6, 2, 7]])

result_array = subtract_row_mean(array)

print("Original Array:")
print(array)

print("\nArray after subtracting the mean of each row:")
print(result_array)

Original Array:
[[1 8 3]
 [4 5 9]
 [6 2 7]]

Array after subtracting the mean of each row:
[[-3.  4. -1.]
 [-2. -1.  3.]
 [ 1. -3.  2.]]


#### 3. How to sort an array by the nth column.

In [46]:
arr = np.random.randint(0,20, (4,4))
print(arr)

[[15  2  9 11]
 [10 14  5  6]
 [ 8 18 19  7]
 [ 9  5 16  5]]


In [52]:
n = 1

print(arr[arr[:, n].argsort()])

[[15  2  9 11]
 [ 9  5 16  5]
 [10 14  5  6]
 [ 8 18 19  7]]


### II. Pandas

#### 1. Get the items of series A not present in series B.

#### 2. Drop the rows where atleast one element is missing in a dataframe.

#### 3. List unique value in a pandas dataframe.

### III. Avocado Dataset

#### 1. Find the correlation matrix to measure the strength of the correlation between variables.

#### 2. Find out the volume of avocado sales has increased in the last 5 years.

#### 3. Find the highest,lowest price for conventional avocado’s in year with location. Show the graph.

#### 4. Find the correlation matrix to measure the strength of the correlation between variables.